'use strict';

const fs      = require('fs');
const path    = require('path');
const puppeteer  = require('puppeteer');
const Handlebars = require('handlebars');

// ---------------------------------------------------------------------------
// Handlebars helpers
// ---------------------------------------------------------------------------

Handlebars.registerHelper('eq', (a, b) => a === b);
Handlebars.registerHelper('isDefined', (v) => v !== undefined && v !== null);

// ---------------------------------------------------------------------------
// Template (compiled once at module load)
// ---------------------------------------------------------------------------

const templatePath = path.join(__dirname, '..', 'templates', 'report.hbs');
const templateSrc  = fs.readFileSync(templatePath, 'utf8');
const template     = Handlebars.compile(templateSrc);

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Derive a safe filename slug from a URL, e.g.:
 *   https://www.example.com/page  →  www.example.com
 */
function domainSlug(url) {
  try {
    return new URL(url).hostname.replace(/[^a-z0-9.-]/gi, '_');
  } catch {
    return 'unknown';
  }
}

/**
 * Format an ISO date string to YYYY-MM-DD.
 */
function dateSlug(isoString) {
  return (isoString || new Date().toISOString()).slice(0, 10);
}

/**
 * Return the hex colour that matches the grade band for a given score.
 */
function meterColor(score) {
  if (score >= 90) return '#16a34a'; // A — green
  if (score >= 80) return '#2563eb'; // B — blue
  if (score >= 70) return '#ca8a04'; // C — amber
  if (score >= 60) return '#ea580c'; // D — orange
  return '#dc2626';                  // F — red
}

/**
 * Count results by status.
 */
function statusCounts(results) {
  return results.reduce(
    (acc, r) => {
      if (r.status === 'pass') acc.passCount++;
      else if (r.status === 'warn') acc.warnCount++;
      else acc.failCount++;
      return acc;
    },
    { passCount: 0, warnCount: 0, failCount: 0 }
  );
}

// ---------------------------------------------------------------------------
// Main export
// ---------------------------------------------------------------------------

/**
 * Generate a PDF report from a JSON audit result object.
 *
 * @param {object} auditJson  The object produced by buildJsonOutput() in index.js.
 * @param {object} [options]
 * @param {string} [options.outputDir]  Directory to write the PDF into (default: <root>/output).
 * @returns {Promise<string>}  Absolute path of the saved PDF file.
 */
async function generatePDF(auditJson, options = {}) {
  const outputDir = options.outputDir ?? path.join(__dirname, '..', 'output');

  // Ensure output directory exists
  fs.mkdirSync(outputDir, { recursive: true });

  const auditedAtFormatted = new Date(auditJson.auditedAt).toLocaleString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
    hour: '2-digit', minute: '2-digit', timeZoneName: 'short',
  });

  // Build template data — augment the audit JSON with derived counts
  const data = {
    ...auditJson,
    auditedAt: auditedAtFormatted,
    meterColor: meterColor(auditJson.totalScore),
    ...statusCounts(auditJson.results),
  };

  const html = template(data);

  // Build output filename
  const domain  = domainSlug(auditJson.url);
  const datePart = dateSlug(auditJson.auditedAt);
  const filename = `seo-report-${domain}-${datePart}.pdf`;
  const outPath  = path.join(outputDir, filename);

  const footerTemplate = `
    <div style="width:100%;padding:0 12mm;display:flex;justify-content:space-between;
                align-items:center;font-size:9px;color:#94a3b8;border-top:1px solid #e2e8f0;">
      <span>Generated by local-seo-audit-tool</span>
      <span>${auditedAtFormatted}</span>
      <span>Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
    </div>`;

  // Render with Puppeteer
  const browser = await puppeteer.launch({ headless: true });
  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: 'networkidle0' });
    await page.pdf({
      path: outPath,
      format: 'A4',
      printBackground: true,
      displayHeaderFooter: true,
      headerTemplate: '<span></span>',
      footerTemplate,
      margin: { top: '10mm', bottom: '14mm', left: '0', right: '0' },
    });
  } finally {
    await browser.close();
  }

  return outPath;
}

module.exports = { generatePDF };
